module.exports = Object.freeze({
  usuarios: require("./usuarioModel"),
  alunos: require("./alunoModel"),
  professores: require("./professorModel"),
  materias: require("./materiaModel"),
  forum: require("./forumModel"),
  duvidas: require("./duvidaModel"),
  respostas: require("./respostaModel"),
  notificacoes: require("./notificacaoModel"),
  contato: require("./contatoModel"),
  conteudos: require("./conteudoModel"),
  formularios: require("./formularioModel"),
  planoEstudo: require("./planoEstudoModel"),
  planoAula: require("./planoAulaModel"),
  assinaturas: require("./assinaturaModel"),
  admin: require("./adminModel"),
  denuncias: require("./denunciaModel"),
  redacoes: require("./redacaoModel"),
  configuracoes: require("./configuracaoModel"),
});
